apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: docker-product-k8s
spec:
  selector:
    matchLabels:
      app: docker-product-k8s
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: docker-product-k8s
    spec:
      containers:
        - name: docker-product-k8s
          image: smilenarula/docker-product:7.0
# Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5656
# The port that the container is running on in the cluster
